// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    TodolistCom: typeof import('./components/TodolistCom/index.vue')['default']
    TodoListItem: typeof import('./components/TodolistCom/modules/TodoListItem.vue')['default']
  }
}

export { }
